default_platform(:ios)

platform :ios do

  desc "Run tests"
  lane :test do
    run_tests(
      project: "CICD Learning/CICD Learning.xcodeproj",
      scheme: "CICD Learning"
    )
  end

  desc "Build app"
  lane :build do
    build_app(
      scheme: "CICD Learning",
      configuration: "Release"
    )
  end

  desc "Deploy to TestFlight"
  lane :beta do
    increment_build_number
    build_app(
      scheme: "CICD Learning"
    )
    upload_to_testflight
  end

end