name: Run tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'

      - name: Install Fastlane
        run: gem install fastlane

      - name: Run Fastlane
        run: fastlane test
